# Generated by Django 5.0.4 on 2024-04-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_app", "0002_remove_collect_amount_donations"),
    ]

    operations = [
        migrations.AddField(
            model_name="collect",
            name="FIO",
            field=models.CharField(default="Никитов Никита Никитович", max_length=100),
        ),
    ]
