# Generated by Django 5.0.4 on 2024-04-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_app", "0003_collect_fio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collect",
            name="FIO",
            field=models.CharField(max_length=100),
        ),
    ]
