# Generated by Django 5.0.4 on 2024-04-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_app", "0004_alter_collect_fio"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="FIO",
            field=models.CharField(default="test", max_length=100),
        ),
    ]
