# Generated by Django 5.0.4 on 2024-04-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_app", "0005_payment_fio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="FIO",
            field=models.CharField(max_length=100),
        ),
    ]
